export const DEFAULT_CALLGRAPH_MAX_NODES = Number.parseInt(process.env.KAIRO_CALLGRAPH_MAX_NODES ?? "500", 10) || 500;
export const DEFAULT_CALLGRAPH_MAX_EDGES = Number.parseInt(process.env.KAIRO_CALLGRAPH_MAX_EDGES ?? "1500", 10) || 1500;
export const DEFAULT_CALLGRAPH_PREVIEW_NODES = 30;
export const DEFAULT_CALLGRAPH_PREVIEW_EDGES = 90;
export const DEFAULT_CALLGRAPH_TOP_NODES = 10;
export const DEFAULT_CALLGRAPH_ARTIFACT_TTL_MS = 30 * 60 * 1000;
