export const DEFAULT_PREVIEW_CHARS = 800;
export const MIN_PREVIEW_CHARS = 240;
export const MIN_EVIDENCE_ITEMS_FLOOR = 1;
export const MIN_EVIDENCE_EXCERPT_CHARS = 120;
export const MIN_FALLBACK_EXCERPT_CHARS = 40;
export const DEFAULT_ELASTIC_WINDOW_PCT = 0.05;
export const DEFAULT_DIFF_CHARS = 2000;
export const MIN_DIFF_CHARS = 800;
