/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ChunkResult {
  text: string
  startByte: number
  endByte: number
  startToken: number
  endToken: number
}
export interface DiffResult {
  diff: string
  added: number
  removed: number
}
export declare function diffUnified(oldText: string, newText: string, contextLines: number): DiffResult
export interface SyntaxIssue {
  line: number
  column: number
  message: string
}
export declare function validateSyntax(language: string, content: string): Array<SyntaxIssue>
export declare function cosineScores(query: Float32Array, vectors: Array<Float32Array>): Array<number>
export declare class SmartChunker {
  constructor(modelPath: string)
  chunk(text: string, maxTokens: number, overlap: number): Array<ChunkResult>
}
