/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ChunkResult {
  text: string
  startByte: number
  endByte: number
  startToken: number
  endToken: number
}
export interface DiffResult {
  diff: string
  added: number
  removed: number
}
export declare function diffUnified(oldText: string, newText: string, contextLines: number): DiffResult
export interface NativeSearchCoreOptions {
  writerMemoryMb?: number
  kairoVersion?: string
  repoId?: string
}
export interface NativeIndexDoc {
  kind: string
  repoId: string
  path?: string
  ext?: string
  mtimeMs?: number
  contentHash?: string
  content?: string
  symbols?: Array<string>
  pathDepth?: number
  callgraphRank?: number
  chunkId?: string
  docPath?: string
  headingPath?: Array<string>
  scope?: string
  text?: string
}
export interface NativeDeleteTarget {
  kind: string
  repoId: string
  path?: string
  chunkId?: string
}
export interface NativeSearchQuery {
  kind: string
  query: string
  repoIds?: Array<string>
  limit: number
  fileTypes?: Array<string>
  scopes?: Array<string>
  debug?: boolean
}
export interface NativeSearchHit {
  kind: string
  repoId: string
  path: string
  chunkId?: string
  score: number
  scope?: string
  signals?: Array<string>
  meta?: Record<string, string>
}
export interface NativeSearchStats {
  docCount: number
  segmentCount: number
  indexVersion: number
  schemaVersion: number
  writeEnabled: boolean
}
export interface SymbolicSolverEvidence {
  snippet?: string
  note?: string
}
export interface SymbolicSolverDiagnostic {
  code: string
  severity: string
  message: string
  filePath?: string
  line?: number
  column?: number
  evidence?: SymbolicSolverEvidence
}
export interface SymbolicSolverConstraint {
  kind: string
  text: string
  scopeKey: string
  line: number
  column: number
}
export interface SymbolicSolverInput {
  filePath: string
  content: string
  constraints: Array<SymbolicSolverConstraint>
  maxPaths: number
  maxConstraints: number
  timeSliceMs: number
}
export interface SymbolicSolverStats {
  durationMs?: number
  pathsExplored?: number
  constraintsBuilt?: number
}
export interface SymbolicSolverResult {
  diagnostics: Array<SymbolicSolverDiagnostic>
  degradedReasons?: Array<string>
  stats?: SymbolicSolverStats
}
export declare function symbolicSolve(input: SymbolicSolverInput): SymbolicSolverResult
export interface SyntaxIssue {
  line: number
  column: number
  message: string
}
export declare function validateSyntax(language: string, content: string): Array<SyntaxIssue>
export declare function cosineScores(query: Float32Array, vectors: Array<Float32Array>): Array<number>
export declare class SmartChunker {
  constructor(modelPath: string)
  chunk(text: string, maxTokens: number, overlap: number): Array<ChunkResult>
}
export declare class NativeSearchCore {
  constructor(indexDir: string, options?: NativeSearchCoreOptions | undefined | null)
  upsert(doc: NativeIndexDoc): void
  upsertMany(docs: Array<NativeIndexDoc>): void
  deleteDoc(target: NativeDeleteTarget): void
  commit(): void
  reset(): void
  search(query: NativeSearchQuery): Array<NativeSearchHit>
  close(): void
  stats(): NativeSearchStats
}
